version: 0.2

env:
  variables:
    VITE_SOME_KEY: "1289hk"
    VITE_DB_NAME: "estoesunabasededatos"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 16
      # install npm
      - npm install

  build:
    commands:
      # run build script
      - npm run-script build

artifacts:
  # include all files required to run application
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
